### PR TITLE
Fix uncaught error on login

### PR DESCRIPTION
**Pull request by LedruRollin**
**Problem**
When the user enters wrong ids, an unexpected error is displayed

**Solution**
Fix the bug : instead of being propagated, the login error was not treated

### CODE REVIEW

**Comment by frankrousseau** [comment]
This pass call was there on purpose. The main idea is to propose a proper auth failed exception. Can you tell more about what you want to achieve?

**Comment by LedruRollin** [comment]
> This pass call was there on purpose. The main idea is to propose a proper auth failed exception. Can you tell more about what you want to achieve?

This is a problem I encountered on my setup : on a bad login, the `check_status` function detects a 400 error and raises a `ParameterException`. This exception propagates in the `post(path, data)` function and eventually in the `log_in` function. The actual implementation of this function lets the error pass and the function continues (resulting in the end in an empty `token` which I could handle, but it doesn't seem really great in terms of implementation). It made sense to me to pursue the propagation of the error with this raise statement, but maybe I'm missing something.

**Comment by frankrousseau** [comment]
It's better to raise an auth failed exception than raising the parameter exception again.

**Comment by LedruRollin** [comment]
Yeah I agree it's useless to have two exceptions for the same issue. But since `tokens` is empty, the auth failed exception is never actually raised. Here is the associated code portion ([code](https://github.com/cgwire/gazu/blob/d7f78eefca5b449d5a217ef7347b841da40b081a/gazu/__init__.py#L30)):
```
    if "login" in tokens and tokens.get("login", False) == False:
        raise AuthFailedException
```
Should this condition be modified ?

**Pull request merged**
