### PR TITLE
Replace deprecated methods by valid ones. Add instances method

### PR DESCRIPTION
**Pull request by pcharmoille**
Hi, first pull request from the Unit Team. 
This is a bit messy for the moment but next time we will try to create branches for each problems and clean our commits (we may squashed them if you want).

**Problems**
- some methods used deprecated methods while there was updated one available
- some methods were using old named method and crashing
- we were missing a methods to retrieve an instance from its name

**Solutions**
use non deprecated methods
fix method name
added new method to manipulate instances :
- `get_asset_instance_by_name`

cheers

### CODE REVIEW

**Comment by pcharmoille** [comment]
I just realized that we did not add tests for the new methods. We will do

**Comment by frankrousseau** [comment]
Awesome! Thank you! 

Tell me when you are ready with the tests

**Comment by pcharmoille** [comment]
Tests added.

I also edited the original comment to match the effective changes (I messed up in the first place)

**Comment by frankrousseau** [comment]
You removed four functions in this commit: https://github.com/cgwire/gazu/pull/35/commits/f4e0077659e41e8beb47b0736ccfe7f73cd25799 . Are you sure this is something you wanted to remove?

**Comment by pcharmoille** [comment]
Yes, they already exist. It was an error on our side. sorry for the confusion

**Comment by frankrousseau** [comment]
Ok thank you. I will manage the commit cleaning as soon as possible (probably tomorrow). Then I'll merge it.

**Comment by frankrousseau** [comment]
The rebase didn't close automatically this PR. I have to close it manually. But don't worry your changes are included. I will publish them with the next release (0.6.0).

**Comment by frankrousseau** [comment]
If you can verify, it would be great. It's possible I messed up during the rebase.

**Comment by pcharmoille** [comment]
There are still duplicated methods in `scene.py` coming from https://github.com/cgwire/gazu/commit/1b1fc7b9a6e2979c14b8da0e3f24fe643e02f5fa. 
You can delete our implementation of `all_shots_for_scene`, `add_shot_to_scene`, `remove_shot_from_scene`.

Apart from that everything is ok.

I think that the pull request not closing automatically has to do with our repo not matching your commits since you cleaned them.

**Pull request closed without merging**
