### PR TITLE
added log_out function

### PR DESCRIPTION
**Pull request by Aderemi-Adesada**
**Problem**
no log_out function
**Solution**
added a logout function that Log user out by revoking his auth tokens

### CODE REVIEW

**Comment by frankrousseau** [comment]
Thank you a lot for this contribution @Aderemi-Adesada . 

To be fully functional, this function should clear tokens instead of trying to set new one. Can you fix that?

**Comment by Aderemi-Adesada** [comment]
Ok I will fix it.

**Comment by Aderemi-Adesada** [comment]
The tokens are now set to a empty dictionary

**Comment by frankrousseau** [comment]
Great, thank you!

**Pull request merged**
