### PR TITLE
Fix normalize_model_parameter to accept unicode arguments in python 2

### PR DESCRIPTION
**Pull request by aboellinger**
**Problem**
In python 2, `normalize_model_parameter` raises an `ValueError` when the `id` it receives as an argument is a `unicode`

**Solution**
Test `id` type against `basestring` instead of `str`, which is the base type for `str` and `unicode` in python2 (using the `future` library for python3 compatibility).

### CODE REVIEW

**Comment by frankrousseau** [comment]
Isn't it better to add a condition that handles the `unicode` type?

**Comment by aboellinger** [comment]
Correct me if I am wrong, but that is not an option since the `unicode` type disappeared in python3.

**Comment by aboellinger** [comment]
I can think of another way of testing it if you prefer : 

* If not a dict, convert the id argument to string
* Match it agains an **uuid** regex
  `([a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}){1}`

**Comment by frankrousseau** [comment]
sounds great!

**Comment by aboellinger** [comment]
@frankrousseau 

I have implemented an utility function that generates an uuid-like string from an arbitrary string. 
This way we can conserve human-readability of mocked ids in code (ie `"asset-id"` becomes `fakeid("asset-id")` instead of `"00000000-0000-0000-0000DEADBEEF"` ).

For now I only replaced it in tests that were failing, I can implement it in all other tests but it will take additional time.

**Comment by frankrousseau** [comment]
Awesome, very elegant! Thx

**Pull request merged**
